#variable "env" {}
#variable "tags" {}
#variable "bastion_cidrs" {}
#variable "sg_cidrs" {}
#variable "vpc_id" {}
#variable "instance_type" {}
#variable "subnets" {}
#variable "route53_zone_id" {}
#variable "kms" {}